title: HaveN Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.haven-studios.xyz
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Prisons realm
      category: Uncategorized
    - name: Bedrock server
      category: Uncategorized
    - name: Java server
      category: Uncategorized
    - name: Discord bot
      category: Uncategorized
    - name: Wiki
      category: Uncategorized
    - name: Website
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/82a5562e-5f22-476e-b963-60e37337a41d.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories: []
  description: Is the realm or a server down? Check here for frequent status
    updates and notes.
  enableCustomHTML: true
  useLargeHeaderDesign: false
